package com.polsl.roadtracker.database.entity;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "THROTTLE_POSITION_DATA".
*/
public class ThrottlePositionDataDao extends AbstractDao<ThrottlePositionData, Void> {

    public static final String TABLENAME = "THROTTLE_POSITION_DATA";

    /**
     * Properties of entity ThrottlePositionData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Timestamp = new Property(0, Long.class, "timestamp", false, "TIMESTAMP");
        public final static Property Value = new Property(1, float.class, "value", false, "VALUE");
        public final static Property RouteId = new Property(2, Long.class, "routeId", false, "ROUTE_ID");
    }

    private Query<ThrottlePositionData> routeData_ThrottlePositionDataListQuery;

    public ThrottlePositionDataDao(DaoConfig config) {
        super(config);
    }
    
    public ThrottlePositionDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"THROTTLE_POSITION_DATA\" (" + //
                "\"TIMESTAMP\" INTEGER," + // 0: timestamp
                "\"VALUE\" REAL NOT NULL ," + // 1: value
                "\"ROUTE_ID\" INTEGER);"); // 2: routeId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_THROTTLE_POSITION_DATA_TIMESTAMP ON THROTTLE_POSITION_DATA" +
                " (\"TIMESTAMP\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"THROTTLE_POSITION_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ThrottlePositionData entity) {
        stmt.clearBindings();
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(1, timestamp);
        }
        stmt.bindDouble(2, entity.getValue());
 
        Long routeId = entity.getRouteId();
        if (routeId != null) {
            stmt.bindLong(3, routeId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ThrottlePositionData entity) {
        stmt.clearBindings();
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(1, timestamp);
        }
        stmt.bindDouble(2, entity.getValue());
 
        Long routeId = entity.getRouteId();
        if (routeId != null) {
            stmt.bindLong(3, routeId);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ThrottlePositionData readEntity(Cursor cursor, int offset) {
        ThrottlePositionData entity = new ThrottlePositionData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // timestamp
            cursor.getFloat(offset + 1), // value
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // routeId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ThrottlePositionData entity, int offset) {
        entity.setTimestamp(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setValue(cursor.getFloat(offset + 1));
        entity.setRouteId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ThrottlePositionData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ThrottlePositionData entity) {
        return null;
    }

    @Override
    public boolean hasKey(ThrottlePositionData entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "throttlePositionDataList" to-many relationship of RouteData. */
    public List<ThrottlePositionData> _queryRouteData_ThrottlePositionDataList(Long routeId) {
        synchronized (this) {
            if (routeData_ThrottlePositionDataListQuery == null) {
                QueryBuilder<ThrottlePositionData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RouteId.eq(null));
                queryBuilder.orderRaw("T.'TIMESTAMP' ASC");
                routeData_ThrottlePositionDataListQuery = queryBuilder.build();
            }
        }
        Query<ThrottlePositionData> query = routeData_ThrottlePositionDataListQuery.forCurrentThread();
        query.setParameter(0, routeId);
        return query.list();
    }

}
